---
server:
  port: 8071
spring:
  application:
    name: gotSaintWho
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://8.210.28.169:8050/gotsaintwho?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
  jpa:
    database: MySQL
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
system:
  config:
    imageSavePath: /usr/local/androidImages/